const deathNoteData = {
    title: "Death Note",
    chapters: {
        1: {
            title: "Page 1-12",
            pages: [
                "assets/images/Death note/Page_001.jpg",
                "assets/images/Death note/Page_002.jpg",
                "assets/images/Death note/Page_003.jpg",
                "assets/images/Death note/Page_004.jpg",
                "assets/images/Death note/Page_005.jpg",
                "assets/images/Death note/Page_006.jpg",
                "assets/images/Death note/Page_007.jpg",
                "assets/images/Death note/Page_008.jpg",
                "assets/images/Death note/Page_009.jpg",
                "assets/images/Death note/Page_010.jpg",
                "assets/images/Death note/Page_011.jpg",
                "assets/images/Death note/Page_012.jpg",
            ]
        },
        2: {
            title: "Page 13-24",
            pages: [
                "assets/images/Death note/Page_013.jpg",
                "assets/images/Death note/Page_014.jpg",
                "assets/images/Death note/Page_015.jpg",
                "assets/images/Death note/Page_016.jpg",
                "assets/images/Death note/Page_017.jpg",
                "assets/images/Death note/Page_018.jpg",
                "assets/images/Death note/Page_019.jpg",
                "assets/images/Death note/Page_020.jpg",
                "assets/images/Death note/Page_021.jpg",
                "assets/images/Death note/Page_022.jpg",
                "assets/images/Death note/Page_023.jpg",
                "assets/images/Death note/Page_024.jpg",
            ]
        },
        3: {
            title: "Page 25-36",
            pages: [
                "assets/images/Death note/Page_025.jpg",
                "assets/images/Death note/Page_026.jpg",
                "assets/images/Death note/Page_027.jpg",
                "assets/images/Death note/Page_028.jpg",
                "assets/images/Death note/Page_029.jpg",
                "assets/images/Death note/Page_030.jpg",
                "assets/images/Death note/Page_031.jpg",
                "assets/images/Death note/Page_032.jpg",
                "assets/images/Death note/Page_033.jpg",
                "assets/images/Death note/Page_034.jpg",
                "assets/images/Death note/Page_035.jpg",
                "assets/images/Death note/Page_036.jpg",
            ]
        },
        4: {
            title: "Page 37-48",
            pages: [
                "assets/images/Death note/Page_037.jpg",
                "assets/images/Death note/Page_038.jpg",
                "assets/images/Death note/Page_039.jpg",
                "assets/images/Death note/Page_040.jpg",
                "assets/images/Death note/Page_041.jpg",
                "assets/images/Death note/Page_042.jpg",
                "assets/images/Death note/Page_043.jpg",
                "assets/images/Death note/Page_044.jpg",
                "assets/images/Death note/Page_045.jpg",
                "assets/images/Death note/Page_046.jpg",
                "assets/images/Death note/Page_047.jpg",
                "assets/images/Death note/Page_048.jpg",
            ]
        },
        5: {
            title: "Page 49-60",
            pages: [
                "assets/images/Death note/Page_049.jpg",
                "assets/images/Death note/Page_050.jpg",
                "assets/images/Death note/Page_051.jpg",
                "assets/images/Death note/Page_052.jpg",
                "assets/images/Death note/Page_053.jpg",
                "assets/images/Death note/Page_054.jpg",
                "assets/images/Death note/Page_055.jpg",
                "assets/images/Death note/Page_056.jpg",
                "assets/images/Death note/Page_057.jpg",
                "assets/images/Death note/Page_058.jpg",
                "assets/images/Death note/Page_059.jpg",
                "assets/images/Death note/Page_060.jpg",
            ]
        },
        6: {
            title: "Page 61-72",
            pages: [
                "assets/images/Death note/Page_061.jpg",
                "assets/images/Death note/Page_062.jpg",
                "assets/images/Death note/Page_063.jpg",
                "assets/images/Death note/Page_064.jpg",
                "assets/images/Death note/Page_065.jpg",
                "assets/images/Death note/Page_066.jpg",
                "assets/images/Death note/Page_067.jpg",
                "assets/images/Death note/Page_068.jpg",
                "assets/images/Death note/Page_069.jpg",
                "assets/images/Death note/Page_070.jpg",
                "assets/images/Death note/Page_071.jpg",
                "assets/images/Death note/Page_072.jpg",
            ]
        },
        7: {
            title: "Page 73-84",
            pages: [
                "assets/images/Death note/Page_073.jpg",
                "assets/images/Death note/Page_074.jpg",
                "assets/images/Death note/Page_075.jpg",
                "assets/images/Death note/Page_076.jpg",
                "assets/images/Death note/Page_077.jpg",
                "assets/images/Death note/Page_078.jpg",
                "assets/images/Death note/Page_079.jpg",
                "assets/images/Death note/Page_080.jpg",
                "assets/images/Death note/Page_081.jpg",
                "assets/images/Death note/Page_082.jpg",
                "assets/images/Death note/Page_083.jpg",
                "assets/images/Death note/Page_084.jpg",
            ]
        },
        8: {
            title: "Page 85-96",
            pages: [
                "assets/images/Death note/Page_085.jpg",
                "assets/images/Death note/Page_086.jpg",
                "assets/images/Death note/Page_087.jpg",
                "assets/images/Death note/Page_088.jpg",
                "assets/images/Death note/Page_089.jpg",
                "assets/images/Death note/Page_090.jpg",
                "assets/images/Death note/Page_091.jpg",
                "assets/images/Death note/Page_092.jpg",
                "assets/images/Death note/Page_093.jpg",
                "assets/images/Death note/Page_094.jpg",
                "assets/images/Death note/Page_095.jpg",
                "assets/images/Death note/Page_096.jpg",
            ]
        },
        9: {
            title: "Page 97-108",
            pages: [
                "assets/images/Death note/Page_097.jpg",
                "assets/images/Death note/Page_098.jpg",
                "assets/images/Death note/Page_099.jpg",
                "assets/images/Death note/Page_100.jpg",
                "assets/images/Death note/Page_101.jpg",
                "assets/images/Death note/Page_102.jpg",
                "assets/images/Death note/Page_103.jpg",
                "assets/images/Death note/Page_104.jpg",
                "assets/images/Death note/Page_105.jpg",
                "assets/images/Death note/Page_106.jpg",
                "assets/images/Death note/Page_107.jpg",
                "assets/images/Death note/Page_108.jpg",
            ]
        },
        10: {
            title: "Page 109-120",
            pages: [
                "assets/images/Death note/Page_109.jpg",
                "assets/images/Death note/Page_110.jpg",
                "assets/images/Death note/Page_111.jpg",
                "assets/images/Death note/Page_112.jpg",
                "assets/images/Death note/Page_113.jpg",
                "assets/images/Death note/Page_114.jpg",
                "assets/images/Death note/Page_115.jpg",
                "assets/images/Death note/Page_116.jpg",
                "assets/images/Death note/Page_117.jpg",
                "assets/images/Death note/Page_118.jpg",
                "assets/images/Death note/Page_119.jpg",
                "assets/images/Death note/Page_120.jpg",
            ]
        },
        11: {
            title: "Page 121-132",
            pages: [
                "assets/images/Death note/Page_121.jpg",
                "assets/images/Death note/Page_122.jpg",
                "assets/images/Death note/Page_123.jpg",
                "assets/images/Death note/Page_124.jpg",
                "assets/images/Death note/Page_125.jpg",
                "assets/images/Death note/Page_126.jpg",
                "assets/images/Death note/Page_127.jpg",
                "assets/images/Death note/Page_128.jpg",
                "assets/images/Death note/Page_129.jpg",
                "assets/images/Death note/Page_130.jpg",
                "assets/images/Death note/Page_131.jpg",
                "assets/images/Death note/Page_132.jpg",
            ]
        },
        12: {
            title: "Page 133-144",
            pages: [
                "assets/images/Death note/Page_133.jpg",
                "assets/images/Death note/Page_134.jpg",
                "assets/images/Death note/Page_135.jpg",
                "assets/images/Death note/Page_136.jpg",
                "assets/images/Death note/Page_137.jpg",
                "assets/images/Death note/Page_138.jpg",
                "assets/images/Death note/Page_139.jpg",
                "assets/images/Death note/Page_140.jpg",
                "assets/images/Death note/Page_141.jpg",
                "assets/images/Death note/Page_142.jpg",
                "assets/images/Death note/Page_143.jpg",
                "assets/images/Death note/Page_144.jpg",
            ]
        },
        13: {
            title: "Page 145-156",
            pages: [
                "assets/images/Death note/Page_145.jpg",
                "assets/images/Death note/Page_146.jpg",
                "assets/images/Death note/Page_147.jpg",
                "assets/images/Death note/Page_148.jpg",
                "assets/images/Death note/Page_149.jpg",
                "assets/images/Death note/Page_150.jpg",
                "assets/images/Death note/Page_151.jpg",
                "assets/images/Death note/Page_152.jpg",
                "assets/images/Death note/Page_153.jpg",
                "assets/images/Death note/Page_154.jpg",
                "assets/images/Death note/Page_155.jpg",
                "assets/images/Death note/Page_156.jpg",
            ]
        },
        14: {
            title: "Page 157-168",
            pages: [
                "assets/images/Death note/Page_157.jpg",
                "assets/images/Death note/Page_158.jpg",
                "assets/images/Death note/Page_159.jpg",
                "assets/images/Death note/Page_160.jpg",
                "assets/images/Death note/Page_161.jpg",
                "assets/images/Death note/Page_162.jpg",
                "assets/images/Death note/Page_163.jpg",
                "assets/images/Death note/Page_164.jpg",
                "assets/images/Death note/Page_165.jpg",
                "assets/images/Death note/Page_166.jpg",
                "assets/images/Death note/Page_167.jpg",
                "assets/images/Death note/Page_168.jpg",
            ]
        },
        15: {
            title: "Page 169-180",
            pages: [
                "assets/images/Death note/Page_169.jpg",
                "assets/images/Death note/Page_170.jpg",
                "assets/images/Death note/Page_171.jpg",
                "assets/images/Death note/Page_172.jpg",
                "assets/images/Death note/Page_173.jpg",
                "assets/images/Death note/Page_174.jpg",
                "assets/images/Death note/Page_175.jpg",
                "assets/images/Death note/Page_176.jpg",
                "assets/images/Death note/Page_177.jpg",
                "assets/images/Death note/Page_178.jpg",
                "assets/images/Death note/Page_179.jpg",
                "assets/images/Death note/Page_180.jpg",
            ]
        },
        16: {
            title: "Page 181-192",
            pages: [
                "assets/images/Death note/Page_181.jpg",
                "assets/images/Death note/Page_182.jpg",
                "assets/images/Death note/Page_183.jpg",
                "assets/images/Death note/Page_184.jpg",
                "assets/images/Death note/Page_185.jpg",
                "assets/images/Death note/Page_186.jpg",
                "assets/images/Death note/Page_187.jpg",
                "assets/images/Death note/Page_188.jpg",
                "assets/images/Death note/Page_189.jpg",
                "assets/images/Death note/Page_190.jpg",
                "assets/images/Death note/Page_191.jpg",
                "assets/images/Death note/Page_192.jpg",
            ]
        },
        17: {
            title: "Page 193-201",
            pages: [
                "assets/images/Death note/Page_193.jpg",
                "assets/images/Death note/Page_194.jpg",
                "assets/images/Death note/Page_195.jpg",
                "assets/images/Death note/Page_196.jpg",
                "assets/images/Death note/Page_197.jpg",
                "assets/images/Death note/Page_198.jpg",
                "assets/images/Death note/Page_199.jpg",
                "assets/images/Death note/Page_200.jpg",
                "assets/images/Death note/Page_201.jpg",
            ]
        },
        18: {
            title: "Vol 2: Page 1-12",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_001.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_002.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_003.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_004.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_005.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_006.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_007.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_008.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_009.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_010.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_011.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_012.jpg",
            ]
        },
        19: {
            title: "Vol 2: Page 13-24",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_013.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_014.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_015.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_016.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_017.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_018.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_019.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_020.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_021.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_022.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_023.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_024.jpg",
            ]
        },
        20: {
            title: "Vol 2: Page 25-36",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_025.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_026.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_027.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_028.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_029.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_030.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_031.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_032.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_033.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_034.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_035.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_036.jpg",
            ]
        },
        21: {
            title: "Vol 2: Page 37-48",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_037.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_038.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_039.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_040.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_041.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_042.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_043.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_044.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_045.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_046.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_047.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_048.jpg",
            ]
        },
        22: {
            title: "Vol 2: Page 49-60",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_049.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_050.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_051.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_052.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_053.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_054.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_055.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_056.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_057.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_058.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_059.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_060.jpg",
            ]
        },
        23: {
            title: "Vol 2: Page 61-72",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_061.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_062.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_063.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_064.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_065.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_066.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_067.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_068.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_069.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_070.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_071.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_072.jpg",
            ]
        },
        24: {
            title: "Vol 2: Page 73-84",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_073.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_074.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_075.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_076.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_077.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_078.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_079.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_080.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_081.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_082.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_083.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_084.jpg",
            ]
        },
        25: {
            title: "Vol 2: Page 85-96",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_085.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_086.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_087.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_088.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_089.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_090.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_091.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_092.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_093.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_094.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_095.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_096.jpg",
            ]
        },
        26: {
            title: "Vol 2: Page 97-108",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_097.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_098.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_099.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_100.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_101.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_102.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_103.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_104.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_105.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_106.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_107.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_108.jpg",
            ]
        },
        27: {
            title: "Vol 2: Page 109-120",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_109.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_110.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_111.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_112.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_113.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_114.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_115.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_116.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_117.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_118.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_119.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_120.jpg",
            ]
        },
        28: {
            title: "Vol 2: Page 121-132",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_121.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_122.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_123.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_124.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_125.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_126.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_127.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_128.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_129.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_130.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_131.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_132.jpg",
            ]
        },
        29: {
            title: "Vol 2: Page 133-144",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_133.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_134.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_135.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_136.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_137.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_138.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_139.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_140.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_141.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_142.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_143.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_144.jpg",
            ]
        },
        30: {
            title: "Vol 2: Page 145-156",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_145.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_146.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_147.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_148.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_149.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_150.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_151.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_152.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_153.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_154.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_155.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_156.jpg",
            ]
        },
        31: {
            title: "Vol 2: Page 157-168",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_157.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_158.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_159.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_160.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_161.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_162.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_163.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_164.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_165.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_166.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_167.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_168.jpg",
            ]
        },
        32: {
            title: "Vol 2: Page 169-180",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_169.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_170.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_171.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_172.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_173.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_174.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_175.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_176.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_177.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_178.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_179.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_180.jpg",
            ]
        },
        33: {
            title: "Vol 2: Page 181-192",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_181.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_182.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_183.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_184.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_185.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_186.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_187.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_188.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_189.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_190.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_191.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_192.jpg",
            ]
        },
        34: {
            title: "Vol 2: Page 193-198",
            pages: [
                "assets/images/Death note Volume 2/Page_Vol2_193.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_194.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_195.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_196.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_197.jpg",
                "assets/images/Death note Volume 2/Page_Vol2_198.jpg",
            ]
        },
        35: {
            title: "Vol 3: Page 1-12",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_001.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_002.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_003.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_004.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_005.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_006.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_007.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_008.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_009.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_010.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_011.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_012.jpg",
            ]
        },
        36: {
            title: "Vol 3: Page 13-24",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_013.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_014.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_015.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_016.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_017.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_018.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_019.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_020.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_021.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_022.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_023.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_024.jpg",
            ]
        },
        37: {
            title: "Vol 3: Page 25-36",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_025.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_026.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_027.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_028.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_029.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_030.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_031.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_032.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_033.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_034.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_035.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_036.jpg",
            ]
        },
        38: {
            title: "Vol 3: Page 37-48",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_037.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_038.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_039.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_040.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_041.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_042.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_043.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_044.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_045.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_046.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_047.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_048.jpg",
            ]
        },
        39: {
            title: "Vol 3: Page 49-60",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_049.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_050.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_051.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_052.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_053.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_054.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_055.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_056.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_057.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_058.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_059.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_060.jpg",
            ]
        },
        40: {
            title: "Vol 3: Page 61-72",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_061.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_062.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_063.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_064.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_065.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_066.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_067.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_068.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_069.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_070.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_071.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_072.jpg",
            ]
        },
        41: {
            title: "Vol 3: Page 73-84",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_073.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_074.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_075.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_076.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_077.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_078.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_079.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_080.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_081.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_082.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_083.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_084.jpg",
            ]
        },
        42: {
            title: "Vol 3: Page 85-96",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_085.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_086.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_087.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_088.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_089.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_090.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_091.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_092.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_093.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_094.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_095.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_096.jpg",
            ]
        },
        43: {
            title: "Vol 3: Page 97-108",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_097.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_098.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_099.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_100.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_101.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_102.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_103.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_104.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_105.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_106.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_107.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_108.jpg",
            ]
        },
        44: {
            title: "Vol 3: Page 109-120",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_109.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_110.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_111.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_112.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_113.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_114.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_115.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_116.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_117.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_118.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_119.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_120.jpg",
            ]
        },
        45: {
            title: "Vol 3: Page 121-132",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_121.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_122.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_123.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_124.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_125.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_126.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_127.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_128.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_129.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_130.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_131.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_132.jpg",
            ]
        },
        46: {
            title: "Vol 3: Page 133-144",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_133.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_134.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_135.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_136.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_137.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_138.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_139.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_140.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_141.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_142.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_143.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_144.jpg",
            ]
        },
        47: {
            title: "Vol 3: Page 145-156",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_145.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_146.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_147.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_148.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_149.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_150.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_151.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_152.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_153.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_154.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_155.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_156.jpg",
            ]
        },
        48: {
            title: "Vol 3: Page 157-168",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_157.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_158.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_159.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_160.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_161.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_162.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_163.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_164.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_165.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_166.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_167.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_168.jpg",
            ]
        },
        49: {
            title: "Vol 3: Page 169-180",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_169.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_170.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_171.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_172.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_173.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_174.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_175.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_176.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_177.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_178.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_179.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_180.jpg",
            ]
        },
        50: {
            title: "Vol 3: Page 181-192",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_181.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_182.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_183.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_184.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_185.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_186.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_187.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_188.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_189.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_190.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_191.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_192.jpg",
            ]
        },
        51: {
            title: "Vol 3: Page 193-204",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_193.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_194.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_195.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_196.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_197.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_198.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_199.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_200.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_201.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_202.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_203.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_204.jpg",
            ]
        },
        52: {
            title: "Vol 3: Page 205-216",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_205.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_206.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_207.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_208.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_209.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_210.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_211.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_212.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_213.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_214.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_215.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_216.jpg",
            ]
        },
        53: {
            title: "Vol 3: Page 217-228",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_217.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_218.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_219.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_220.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_221.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_222.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_223.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_224.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_225.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_226.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_227.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_228.jpg",
            ]
        },
        54: {
            title: "Vol 3: Page 229-240",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_229.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_230.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_231.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_232.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_233.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_234.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_235.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_236.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_237.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_238.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_239.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_240.jpg",
            ]
        },
        55: {
            title: "Vol 3: Page 241-252",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_241.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_242.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_243.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_244.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_245.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_246.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_247.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_248.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_249.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_250.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_251.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_252.jpg",
            ]
        },
        56: {
            title: "Vol 3: Page 253-264",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_253.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_254.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_255.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_256.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_257.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_258.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_259.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_260.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_261.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_262.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_263.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_264.jpg",
            ]
        },
        57: {
            title: "Vol 3: Page 265-276",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_265.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_266.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_267.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_268.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_269.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_270.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_271.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_272.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_273.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_274.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_275.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_276.jpg",
            ]
        },
        58: {
            title: "Vol 3: Page 277-288",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_277.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_278.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_279.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_280.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_281.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_282.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_283.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_284.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_285.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_286.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_287.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_288.jpg",
            ]
        },
        59: {
            title: "Vol 3: Page 289-300",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_289.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_290.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_291.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_292.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_293.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_294.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_295.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_296.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_297.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_298.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_299.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_300.jpg",
            ]
        },
        60: {
            title: "Vol 3: Page 301-312",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_301.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_302.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_303.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_304.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_305.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_306.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_307.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_308.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_309.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_310.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_311.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_312.jpg",
            ]
        },
        61: {
            title: "Vol 3: Page 313-324",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_313.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_314.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_315.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_316.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_317.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_318.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_319.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_320.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_321.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_322.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_323.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_324.jpg",
            ]
        },
        62: {
            title: "Vol 3: Page 325-336",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_325.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_326.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_327.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_328.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_329.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_330.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_331.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_332.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_333.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_334.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_335.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_336.jpg",
            ]
        },
        63: {
            title: "Vol 3: Page 337-348",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_337.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_338.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_339.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_340.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_341.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_342.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_343.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_344.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_345.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_346.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_347.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_348.jpg",
            ]
        },
        64: {
            title: "Vol 3: Page 349-360",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_349.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_350.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_351.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_352.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_353.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_354.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_355.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_356.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_357.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_358.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_359.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_360.jpg",
            ]
        },
        65: {
            title: "Vol 3: Page 361-372",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_361.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_362.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_363.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_364.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_365.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_366.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_367.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_368.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_369.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_370.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_371.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_372.jpg",
            ]
        },
        66: {
            title: "Vol 3: Page 373-383",
            pages: [
                "assets/images/Deathh note volume 3/Page_Vol3_373.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_374.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_375.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_376.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_377.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_378.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_379.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_380.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_381.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_382.jpg",
                "assets/images/Deathh note volume 3/Page_Vol3_383.jpg",
            ]
        },
    }
};
