const onePieceData = {
    "title": "One Piece",
    "isText": false,
    "chapters": {
        "1": {
            "title": "Romance Dawn",
            "pages": [
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_01.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_02.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_03.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_04.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_05.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_06.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_07.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_08.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_09.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_10.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_11.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_12.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_13.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_14.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_15.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_16.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_17.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_18.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_19.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_20.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_21.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_22.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_23.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_24.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_25.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_26.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_27.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_28.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_29.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_30.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_31.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_32.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_33.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_34.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_35.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_36.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_37.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_38.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_39.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_40.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_41.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_42.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_43.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_44.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_45.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_46.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_47.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_48.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_49.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_50.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_51.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_52.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_53.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_54.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_55.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_56.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_01_57.jpg"
            ]
        },
        "2": {
            "title": "They Call Him 'Straw Hat Luffy'",
            "pages": [
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_01.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_02.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_03.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_04.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_05.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_06.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_07.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_08.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_09.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_10.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_11.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_12.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_13.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_14.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_15.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_16.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_17.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_18.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_19.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_20.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_21.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_22.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_23.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_02_24.jpg"
            ]
        },
        "3": {
            "title": "Enter Zoro-Pirate Hunter",
            "pages": [
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_01.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_02.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_03.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_04.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_05.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_06.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_07.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_08.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_09.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_10.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_11.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_12.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_13.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_14.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_15.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_16.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_17.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_18.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_19.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_20.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_21.jpg",
                "https://cdn.onepiecechapters.com/file/opctcb/onepiece/onepiecechapters_03_22.jpg"
            ]
        }
    }
};
